package Entidades;
// Generated 09-24-2019 02:27:54 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cuentas generated by hbm2java
 */
@Entity
@Table(name="cuentas"
    ,schema="public"
)
public class Cuentas  implements java.io.Serializable {


     private String cuenta;
     private String nombre;
     private String tipo;
     private int nivel;
     private String saldo;
     private String rcuenta;
     private String cpadre;
     private Set<Dettransaccion> dettransaccions = new HashSet<Dettransaccion>(0);

    public Cuentas() {
    }

	
    public Cuentas(String cuenta, String nombre, String tipo, int nivel, String saldo, String cpadre) {
        this.cuenta = cuenta;
        this.nombre = nombre;
        this.tipo = tipo;
        this.nivel = nivel;
        this.saldo = saldo;
        this.cpadre = cpadre;
    }
    public Cuentas(String cuenta, String nombre, String tipo, int nivel, String saldo, String rcuenta, String cpadre, Set<Dettransaccion> dettransaccions) {
       this.cuenta = cuenta;
       this.nombre = nombre;
       this.tipo = tipo;
       this.nivel = nivel;
       this.saldo = saldo;
       this.rcuenta = rcuenta;
       this.cpadre = cpadre;
       this.dettransaccions = dettransaccions;
    }
   
     @Id 

    
    @Column(name="cuenta", unique=true, nullable=false, length=50)
    public String getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(String cuenta) {
        this.cuenta = cuenta;
    }

    
    @Column(name="nombre", nullable=false, length=200)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="tipo", nullable=false, length=20)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="nivel", nullable=false)
    public int getNivel() {
        return this.nivel;
    }
    
    public void setNivel(int nivel) {
        this.nivel = nivel;
    }

    
    @Column(name="saldo", nullable=false, length=20)
    public String getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(String saldo) {
        this.saldo = saldo;
    }

    
    @Column(name="rcuenta", length=2)
    public String getRcuenta() {
        return this.rcuenta;
    }
    
    public void setRcuenta(String rcuenta) {
        this.rcuenta = rcuenta;
    }

    
    @Column(name="cpadre", nullable=false, length=50)
    public String getCpadre() {
        return this.cpadre;
    }
    
    public void setCpadre(String cpadre) {
        this.cpadre = cpadre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cuentas")
    public Set<Dettransaccion> getDettransaccions() {
        return this.dettransaccions;
    }
    
    public void setDettransaccions(Set<Dettransaccion> dettransaccions) {
        this.dettransaccions = dettransaccions;
    }




}


