package Entidades;
// Generated 09-24-2019 02:27:54 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Dettransaccion generated by hbm2java
 */
@Entity
@Table(name="dettransaccion"
    ,schema="public"
)
public class Dettransaccion  implements java.io.Serializable {


     private long id;
     private Cuentas cuentas;
     private Transaccion transaccion;
     private BigDecimal cargo;
     private BigDecimal abono;

    public Dettransaccion() {
    }

	
    public Dettransaccion(long id, Cuentas cuentas, Transaccion transaccion) {
        this.id = id;
        this.cuentas = cuentas;
        this.transaccion = transaccion;
    }
    public Dettransaccion(long id, Cuentas cuentas, Transaccion transaccion, BigDecimal cargo, BigDecimal abono) {
       this.id = id;
       this.cuentas = cuentas;
       this.transaccion = transaccion;
       this.cargo = cargo;
       this.abono = abono;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcuenta", nullable=false)
    public Cuentas getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Cuentas cuentas) {
        this.cuentas = cuentas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idtransaccion", nullable=false)
    public Transaccion getTransaccion() {
        return this.transaccion;
    }
    
    public void setTransaccion(Transaccion transaccion) {
        this.transaccion = transaccion;
    }

    
    @Column(name="cargo", precision=16)
    public BigDecimal getCargo() {
        return this.cargo;
    }
    
    public void setCargo(BigDecimal cargo) {
        this.cargo = cargo;
    }

    
    @Column(name="abono", precision=16)
    public BigDecimal getAbono() {
        return this.abono;
    }
    
    public void setAbono(BigDecimal abono) {
        this.abono = abono;
    }




}


