package Entidades;
// Generated 09-24-2019 02:27:54 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Login generated by hbm2java
 */
@Entity
@Table(name="login"
    ,schema="public"
)
public class Login  implements java.io.Serializable {


     private int id;
     private String usuario;
     private String password;
     private String email;
     private Integer codigo;

    public Login() {
    }

	
    public Login(int id, String usuario, String password, String email) {
        this.id = id;
        this.usuario = usuario;
        this.password = password;
        this.email = email;
    }
    public Login(int id, String usuario, String password, String email, Integer codigo) {
       this.id = id;
       this.usuario = usuario;
       this.password = password;
       this.email = email;
       this.codigo = codigo;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="usuario", nullable=false, length=500)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="password", nullable=false, length=700)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="email", nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="codigo")
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }




}


