package Entidades;
// Generated 09-24-2019 02:27:54 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transaccion generated by hbm2java
 */
@Entity
@Table(name="transaccion"
    ,schema="public"
)
public class Transaccion  implements java.io.Serializable {


     private long id;
     private Date fecha;
     private String descripcion;
     private int partida;
     private Set<Dettransaccion> dettransaccions = new HashSet<Dettransaccion>(0);

    public Transaccion() {
    }

	
    public Transaccion(long id, Date fecha, String descripcion, int partida) {
        this.id = id;
        this.fecha = fecha;
        this.descripcion = descripcion;
        this.partida = partida;
    }
    public Transaccion(long id, Date fecha, String descripcion, int partida, Set<Dettransaccion> dettransaccions) {
       this.id = id;
       this.fecha = fecha;
       this.descripcion = descripcion;
       this.partida = partida;
       this.dettransaccions = dettransaccions;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="descripcion", nullable=false, length=500)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="partida", nullable=false)
    public int getPartida() {
        return this.partida;
    }
    
    public void setPartida(int partida) {
        this.partida = partida;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="transaccion")
    public Set<Dettransaccion> getDettransaccions() {
        return this.dettransaccions;
    }
    
    public void setDettransaccions(Set<Dettransaccion> dettransaccions) {
        this.dettransaccions = dettransaccions;
    }




}


